//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worksite
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDevice
    {
        public long DeviceId { get; set; }
        public string Name { get; set; }
        public Nullable<int> InventNo { get; set; }
        public string DeviceType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
