//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worksite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorksiteEntities : DbContext
    {
        public WorksiteEntities()
            : base("name=WorksiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceType> DeviceTypes { get; set; }
        public virtual DbSet<ServiceOrder> ServiceOrders { get; set; }
        public virtual DbSet<ServiceOrders_ServiceStatuses> ServiceOrders_ServiceStatuses { get; set; }
        public virtual DbSet<ServiceOrders_ServiceTypes> ServiceOrders_ServiceTypes { get; set; }
        public virtual DbSet<ServiceStatus> ServiceStatuses { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AllDevice> AllDevices { get; set; }
        public virtual DbSet<AllExpiredService> AllExpiredServices { get; set; }
        public virtual DbSet<AllOpenService> AllOpenServices { get; set; }
        public virtual DbSet<AllService> AllServices { get; set; }
        public virtual DbSet<AllWrongStatusService> AllWrongStatusServices { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
