//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worksite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrders_ServiceStatuses
    {
        public long ServiceOrders_ServiceStatusesId { get; set; }
        public long ServiceOrderId { get; set; }
        public long ServiceStatusId { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ServiceStatus ServiceStatus { get; set; }
        public virtual User User { get; set; }
        
    }
}
