//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worksite
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ServiceOrders = new HashSet<ServiceOrder>();
            this.ServiceOrders_ServiceStatuses = new HashSet<ServiceOrders_ServiceStatuses>();
        }
    
        public long UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public bool Administrator { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> LoginTryCount { get; set; }
        public Nullable<System.DateTime> LastLoginTryDateTime { get; set; }

        public override string ToString()
        {
            return FirstName + " " + LastName;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrder> ServiceOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrders_ServiceStatuses> ServiceOrders_ServiceStatuses { get; set; }
    }
}
