//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worksite
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllOpenService
    {
        public long ServiceOrderId { get; set; }
        public long DeviceId { get; set; }
        public string DeviceName { get; set; }
        public System.DateTime OpenDate { get; set; }
        public string ServiceStatus { get; set; }
        public string Employee { get; set; }
        public long UserId { get; set; }
    }
}
