//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worksite.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllService
    {
        public long ServiceOrderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long DeviceId { get; set; }
        public string DeviceName { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ServiceStatusName { get; set; }
        public Nullable<decimal> ServiceValue { get; set; }
        public string Employee { get; set; }
    }
}
