//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worksite.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrders_ServiceTypes
    {
        public long ServiceOrders_ServiceTypesId { get; set; }
        public long ServiceOrderId { get; set; }
        public long ServiceTypeId { get; set; }
    
        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
